# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AMainWindow.ui'
#
# Created: Thu Mar 15 17:32:36 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 267)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.txtDocuments = QtGui.QLineEdit(self.gridLayoutWidget)
        self.txtDocuments.setEnabled(False)
        self.txtDocuments.setObjectName("txtDocuments")
        self.gridLayout.addWidget(self.txtDocuments, 0, 1, 1, 1)
        self.lblVideos = QtGui.QLabel(self.gridLayoutWidget)
        self.lblVideos.setObjectName("lblVideos")
        self.gridLayout.addWidget(self.lblVideos, 2, 0, 1, 1)
        self.btnDocuments = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnDocuments.setObjectName("btnDocuments")
        self.gridLayout.addWidget(self.btnDocuments, 0, 2, 1, 1)
        self.lblDocuments = QtGui.QLabel(self.gridLayoutWidget)
        self.lblDocuments.setObjectName("lblDocuments")
        self.gridLayout.addWidget(self.lblDocuments, 0, 0, 1, 1)
        self.txtVideos = QtGui.QLineEdit(self.gridLayoutWidget)
        self.txtVideos.setEnabled(False)
        self.txtVideos.setObjectName("txtVideos")
        self.gridLayout.addWidget(self.txtVideos, 2, 1, 1, 1)
        self.lblMusic = QtGui.QLabel(self.gridLayoutWidget)
        self.lblMusic.setObjectName("lblMusic")
        self.gridLayout.addWidget(self.lblMusic, 1, 0, 1, 1)
        self.lblImages = QtGui.QLabel(self.gridLayoutWidget)
        self.lblImages.setObjectName("lblImages")
        self.gridLayout.addWidget(self.lblImages, 3, 0, 1, 1)
        self.btnImages = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnImages.setObjectName("btnImages")
        self.gridLayout.addWidget(self.btnImages, 3, 2, 1, 1)
        self.txtMusic = QtGui.QLineEdit(self.gridLayoutWidget)
        self.txtMusic.setEnabled(False)
        self.txtMusic.setObjectName("txtMusic")
        self.gridLayout.addWidget(self.txtMusic, 1, 1, 1, 1)
        self.btnVideos = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnVideos.setObjectName("btnVideos")
        self.gridLayout.addWidget(self.btnVideos, 2, 2, 1, 1)
        self.btnMusic = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnMusic.setObjectName("btnMusic")
        self.gridLayout.addWidget(self.btnMusic, 1, 2, 1, 1)
        self.txtImages = QtGui.QLineEdit(self.gridLayoutWidget)
        self.txtImages.setEnabled(False)
        self.txtImages.setObjectName("txtImages")
        self.gridLayout.addWidget(self.txtImages, 3, 1, 1, 1)
        self.chkDocuments = QtGui.QCheckBox(self.gridLayoutWidget)
        self.chkDocuments.setText("")
        self.chkDocuments.setObjectName("chkDocuments")
        self.gridLayout.addWidget(self.chkDocuments, 0, 3, 1, 1)
        self.chkMusic = QtGui.QCheckBox(self.gridLayoutWidget)
        self.chkMusic.setText("")
        self.chkMusic.setObjectName("chkMusic")
        self.gridLayout.addWidget(self.chkMusic, 1, 3, 1, 1)
        self.chkVideos = QtGui.QCheckBox(self.gridLayoutWidget)
        self.chkVideos.setText("")
        self.chkVideos.setObjectName("chkVideos")
        self.gridLayout.addWidget(self.chkVideos, 2, 3, 1, 1)
        self.chkImages = QtGui.QCheckBox(self.gridLayoutWidget)
        self.chkImages.setText("")
        self.chkImages.setObjectName("chkImages")
        self.gridLayout.addWidget(self.chkImages, 3, 3, 1, 1)
        self.btnBackup = QtGui.QPushButton(self.centralwidget)
        self.btnBackup.setGeometry(QtCore.QRect(160, 190, 87, 29))
        self.btnBackup.setObjectName("btnBackup")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Qt Backup Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.lblVideos.setText(QtGui.QApplication.translate("MainWindow", "VIDEOS", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDocuments.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDocuments.setText(QtGui.QApplication.translate("MainWindow", "DOCUMENTS", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMusic.setText(QtGui.QApplication.translate("MainWindow", "MUSIC", None, QtGui.QApplication.UnicodeUTF8))
        self.lblImages.setText(QtGui.QApplication.translate("MainWindow", "IMAGES", None, QtGui.QApplication.UnicodeUTF8))
        self.btnImages.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnVideos.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMusic.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackup.setText(QtGui.QApplication.translate("MainWindow", "BACKUP", None, QtGui.QApplication.UnicodeUTF8))

