# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AMainWindow.ui'
#
# Created: Fri Mar 16 09:20:53 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 267)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.txtDocuments = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtDocuments.setEnabled(False)
        self.txtDocuments.setObjectName("txtDocuments")
        self.gridLayout.addWidget(self.txtDocuments, 0, 1, 1, 1)
        self.lblVideos = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblVideos.setObjectName("lblVideos")
        self.gridLayout.addWidget(self.lblVideos, 2, 0, 1, 1)
        self.btnDocuments = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnDocuments.setObjectName("btnDocuments")
        self.gridLayout.addWidget(self.btnDocuments, 0, 2, 1, 1)
        self.lblDocuments = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblDocuments.setObjectName("lblDocuments")
        self.gridLayout.addWidget(self.lblDocuments, 0, 0, 1, 1)
        self.txtVideos = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtVideos.setEnabled(False)
        self.txtVideos.setObjectName("txtVideos")
        self.gridLayout.addWidget(self.txtVideos, 2, 1, 1, 1)
        self.lblMusic = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblMusic.setObjectName("lblMusic")
        self.gridLayout.addWidget(self.lblMusic, 1, 0, 1, 1)
        self.lblImages = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblImages.setObjectName("lblImages")
        self.gridLayout.addWidget(self.lblImages, 3, 0, 1, 1)
        self.btnImages = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnImages.setObjectName("btnImages")
        self.gridLayout.addWidget(self.btnImages, 3, 2, 1, 1)
        self.txtMusic = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtMusic.setEnabled(False)
        self.txtMusic.setObjectName("txtMusic")
        self.gridLayout.addWidget(self.txtMusic, 1, 1, 1, 1)
        self.btnVideos = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnVideos.setObjectName("btnVideos")
        self.gridLayout.addWidget(self.btnVideos, 2, 2, 1, 1)
        self.btnMusic = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnMusic.setObjectName("btnMusic")
        self.gridLayout.addWidget(self.btnMusic, 1, 2, 1, 1)
        self.txtImages = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtImages.setEnabled(False)
        self.txtImages.setObjectName("txtImages")
        self.gridLayout.addWidget(self.txtImages, 3, 1, 1, 1)
        self.chkDocuments = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.chkDocuments.setText("")
        self.chkDocuments.setObjectName("chkDocuments")
        self.gridLayout.addWidget(self.chkDocuments, 0, 3, 1, 1)
        self.chkMusic = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.chkMusic.setText("")
        self.chkMusic.setObjectName("chkMusic")
        self.gridLayout.addWidget(self.chkMusic, 1, 3, 1, 1)
        self.chkVideos = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.chkVideos.setText("")
        self.chkVideos.setObjectName("chkVideos")
        self.gridLayout.addWidget(self.chkVideos, 2, 3, 1, 1)
        self.chkImages = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.chkImages.setText("")
        self.chkImages.setObjectName("chkImages")
        self.gridLayout.addWidget(self.chkImages, 3, 3, 1, 1)
        self.btnBackup = QtWidgets.QPushButton(self.centralwidget)
        self.btnBackup.setGeometry(QtCore.QRect(160, 190, 87, 29))
        self.btnBackup.setObjectName("btnBackup")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Qt Backup Tool", None, -1))
        self.lblVideos.setText(QtWidgets.QApplication.translate("MainWindow", "VIDEOS", None, -1))
        self.btnDocuments.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.lblDocuments.setText(QtWidgets.QApplication.translate("MainWindow", "DOCUMENTS", None, -1))
        self.lblMusic.setText(QtWidgets.QApplication.translate("MainWindow", "MUSIC", None, -1))
        self.lblImages.setText(QtWidgets.QApplication.translate("MainWindow", "IMAGES", None, -1))
        self.btnImages.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btnVideos.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btnMusic.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btnBackup.setText(QtWidgets.QApplication.translate("MainWindow", "BACKUP", None, -1))

